// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

// struct NodeIdent, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct NodeIdent(pub [u8; 32]);
impl Default for NodeIdent { 
  fn default() -> Self { 
    Self([0; 32])
  }
}
impl core::fmt::Debug for NodeIdent {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("NodeIdent")
      .field("bytes", &self.bytes())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for NodeIdent {}
impl<'a> flatbuffers::Follow<'a> for NodeIdent {
  type Inner = &'a NodeIdent;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a NodeIdent>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a NodeIdent {
  type Inner = &'a NodeIdent;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<NodeIdent>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for NodeIdent {
    type Output = NodeIdent;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const NodeIdent as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(1)
    }
}

impl<'a> flatbuffers::Verifiable for NodeIdent {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> NodeIdent {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    bytes: &[u8; 32],
  ) -> Self {
    let mut s = Self([0; 32]);
    s.set_bytes(bytes);
    s
  }

  pub fn bytes(&'a self) -> flatbuffers::Array<'a, u8, 32> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::Array::follow(&self.0, 0) }
  }

  pub fn set_bytes(&mut self, items: &[u8; 32]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::emplace_scalar_array(&mut self.0, 0, items) };
  }

}

pub enum AcceptingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Accepting<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Accepting<'a> {
  type Inner = Accepting<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Accepting<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NODES: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Accepting { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AcceptingArgs<'args>
  ) -> flatbuffers::WIPOffset<Accepting<'bldr>> {
    let mut builder = AcceptingBuilder::new(_fbb);
    if let Some(x) = args.nodes { builder.add_nodes(x); }
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Accepting::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn nodes(&self) -> Option<flatbuffers::Vector<'a, NodeIdent>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, NodeIdent>>>(Accepting::VT_NODES, None)}
  }
}

impl flatbuffers::Verifiable for Accepting<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, NodeIdent>>>("nodes", Self::VT_NODES, false)?
     .finish();
    Ok(())
  }
}
pub struct AcceptingArgs<'a> {
    pub id: i32,
    pub nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, NodeIdent>>>,
}
impl<'a> Default for AcceptingArgs<'a> {
  #[inline]
  fn default() -> Self {
    AcceptingArgs {
      id: 0,
      nodes: None,
    }
  }
}

pub struct AcceptingBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> AcceptingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(Accepting::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_nodes(&mut self, nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , NodeIdent>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Accepting::VT_NODES, nodes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> AcceptingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AcceptingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Accepting<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Accepting<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Accepting");
      ds.field("id", &self.id());
      ds.field("nodes", &self.nodes());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Accepting`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_accepting_unchecked`.
pub fn root_as_accepting(buf: &[u8]) -> Result<Accepting, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Accepting>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Accepting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_accepting_unchecked`.
pub fn size_prefixed_root_as_accepting(buf: &[u8]) -> Result<Accepting, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Accepting>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Accepting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_accepting_unchecked`.
pub fn root_as_accepting_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Accepting<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Accepting<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Accepting` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_accepting_unchecked`.
pub fn size_prefixed_root_as_accepting_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Accepting<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Accepting<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Accepting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Accepting`.
pub unsafe fn root_as_accepting_unchecked(buf: &[u8]) -> Accepting {
  flatbuffers::root_unchecked::<Accepting>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Accepting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Accepting`.
pub unsafe fn size_prefixed_root_as_accepting_unchecked(buf: &[u8]) -> Accepting {
  flatbuffers::size_prefixed_root_unchecked::<Accepting>(buf)
}
#[inline]
pub fn finish_accepting_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Accepting<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_accepting_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Accepting<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
