// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum ConnectingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Connecting<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Connecting<'a> {
  type Inner = Connecting<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Connecting<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_REQUEST_NODES: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Connecting { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ConnectingArgs
  ) -> flatbuffers::WIPOffset<Connecting<'bldr>> {
    let mut builder = ConnectingBuilder::new(_fbb);
    builder.add_id(args.id);
    builder.add_request_nodes(args.request_nodes);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Connecting::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn request_nodes(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Connecting::VT_REQUEST_NODES, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Connecting<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("id", Self::VT_ID, false)?
     .visit_field::<bool>("request_nodes", Self::VT_REQUEST_NODES, false)?
     .finish();
    Ok(())
  }
}
pub struct ConnectingArgs {
    pub id: i32,
    pub request_nodes: bool,
}
impl<'a> Default for ConnectingArgs {
  #[inline]
  fn default() -> Self {
    ConnectingArgs {
      id: 0,
      request_nodes: false,
    }
  }
}

pub struct ConnectingBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ConnectingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: i32) {
    self.fbb_.push_slot::<i32>(Connecting::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_request_nodes(&mut self, request_nodes: bool) {
    self.fbb_.push_slot::<bool>(Connecting::VT_REQUEST_NODES, request_nodes, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ConnectingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ConnectingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Connecting<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Connecting<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Connecting");
      ds.field("id", &self.id());
      ds.field("request_nodes", &self.request_nodes());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Connecting`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_connecting_unchecked`.
pub fn root_as_connecting(buf: &[u8]) -> Result<Connecting, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Connecting>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Connecting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_connecting_unchecked`.
pub fn size_prefixed_root_as_connecting(buf: &[u8]) -> Result<Connecting, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Connecting>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Connecting` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_connecting_unchecked`.
pub fn root_as_connecting_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Connecting<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Connecting<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Connecting` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_connecting_unchecked`.
pub fn size_prefixed_root_as_connecting_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Connecting<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Connecting<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Connecting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Connecting`.
pub unsafe fn root_as_connecting_unchecked(buf: &[u8]) -> Connecting {
  flatbuffers::root_unchecked::<Connecting>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Connecting and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Connecting`.
pub unsafe fn size_prefixed_root_as_connecting_unchecked(buf: &[u8]) -> Connecting {
  flatbuffers::size_prefixed_root_unchecked::<Connecting>(buf)
}
#[inline]
pub fn finish_connecting_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Connecting<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_connecting_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Connecting<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
